blueprints/qa.py
# -*- coding: utf-8 -*-
# @Time    : 2022/5/16 12:48
# @Author  : 张梓锐
# @File    : qa.py
# @Software: PyCharm 
# @Content : 问答进程相关

from flask import Blueprint,render_template, g, request, redirect, url_for, flash
from .forms import QuestionForm,AnswerForm
from models import Question_Model,AnswerModel
from extends import db
from decorators import login_required
from sqlalchemy import or_

bp = Blueprint("qa", __name__, url_prefix="/")


@bp.route('/')
# @login_required
def index():
    questions = Question_Model.query.order_by(db.text("-create_time")).all()
    return render_template("index.html", questions=questions)


@bp.route("/question/public", methods=['GET', 'POST'])
@login_required
def public_question():
    # 判断是否登录，如果没有登录，跳转到登录页面
    if request.method == 'GET':
        return render_template("public_question.html")
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            # print("\n", g.user.id,"\n","\n")
            question = Question_Model(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            return redirect("/")
        else:
            flash("标题或内容格式错误")
            return redirect(url_for("qa.public_question"))


@bp.route("/question/<int:question_id>")
def question_detail(question_id):
    question = Question_Model.query.get(question_id)
    return render_template("detail.html", question=question)


@bp.route('/answer/<int:question_id>', methods=["POST"])
@login_required
def answer(question_id):
    form = AnswerForm(request.form)
    if form.validate():
        content = form.content.data
        answer_model = AnswerModel(content=content,author=g.user,question_id=question_id)
        db.session.add(answer_model)
        db.session.commit()
        return redirect(url_for("qa.question_detail",question_id=question_id))
    else:
        flash("评论失败") # 内含敏感词或者空评论
        return redirect(url_for("qa.question_detail",question_id=question_id))


@bp.route('/search')
def search():
    # /search?q=xxx
    q = request.args.get("q")
    # filter_by:直接使用字段名称
    # filter: 使用模型.字段名称
    questions = Question_Model.query.filter(or_(Question_Model.title.contains(q),Question_Model.content.contains(q))).order_by(db.text("-create_time"))
    return render_template("index.html",questions=questions)

blueprints/user.py
# -*- coding: utf-8 -*-
# @Time    : 2022/5/16 12:48
# @Author  : 张梓锐
# @File    : user.py
# @Software: PyCharm 
# @Content : 用户进程相关

import datetime, string, random

from extends import mail, db
from flask_mail import Message
from models import EmailCaptchaModel,User_Model
from .forms import RegisterForm,LoginForm
from werkzeug.security import generate_password_hash, check_password_hash
from flask import (Blueprint,
                   render_template,
                   request,
                   redirect,
                   url_for,
                   jsonify,
                   session,
                   flash)

bp = Blueprint("user", __name__, url_prefix="/user")


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = User_Model.query.filter_by(email=email).first()
            if user and check_password_hash(user.password, password):
                session['user_id'] = user.id
                return redirect("/")
            else:
                flash("邮箱或密码错误")
                return redirect(url_for("user.login"))
        else:
            flash("邮箱或密码格式错误")
            return redirect(url_for("user.login"))


@bp.route('/logout')
def logout():
    # 清除session中所有的数据
    session.clear()
    return redirect(url_for('user.login'))


@bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            hash_password = generate_password_hash(password)
            user = User_Model(email=email, username=username, password=hash_password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.login"))
        else:
            return redirect(url_for("user.register"))


@bp.route('/captcha', methods=["POST"])
def get_captcha():
    email = request.form.get("email")
    letter = string.ascii_letters + string.digits
    captcha = "".join(random.sample(letter, 4))
    print("\n",captcha,"\n")
    if email:
        message = Message(
            subject='进修馆',
            recipients=['{}'.format(email)],
            body="【进修馆】\n验证码为{}，请妥善保管。".format(captcha)
        )
        mail.send(message)
        captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()
        if captcha_model:
            captcha_model.captcha = captcha
            captcha_model.create_time = datetime.datetime.now()
            db.session.commit()
        else:
            captcha_model = EmailCaptchaModel(email=email, captcha=captcha)
            db.session.add(captcha_model)
            db.session.commit()
            # code:200 成功的请求
        return jsonify({"code": 200})
    else:
        # code:400  客户端错误
        return jsonify({"code": 400, "message":"请先传递邮箱"})
    return

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/init.css')}}">
    {% block head %}{% endblock %}

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
      <a class="navbar-brand" href="#">python问答</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('qa.public_question')}}">发布问答</a>
        </li>

      <form class="form-inline my-2 my-lg-0" method="get" action="{{ url_for('qa.search') }}">
        <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search" name="q">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
      </form>
      </ul>
    <div style="text-align: right;">
          <ul class="navbar-nav mr-auto" >
        {% if user %}
          <li class="nav-item active">
            <a class="nav-link" href="#">{{ user.username }}</a>
          </li>
          <li class="nav-item active" >
            <a class="nav-link" href="{{url_for('user.logout')}}">注销</a>
          </li>
          {% else %}
                <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('user.login') }}">登录</a>
          </li>
          <li class="nav-item active" >
            <a class="nav-link" href="{{url_for('user.register')}}">注册</a>
          </li>
          {% endif %}

        </ul>
    </div>



    </div>
  </div>

</nav>
<div class="container">{% block body %}{% endblock %}</div>
</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block title %}{{ question.title }}{% endblock %}


{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename='css/detail.css') }}">
{% endblock %}


{% block body %}
  <div class="row" style="margin-top: 20px;">
    <div class="col"></div>
    <div class="col-8" style="background-color: #fff;padding: 20px;">
      <h3 class="page-title">{{ question.title }}</h3>
      <p class="question-info">
        <span>作者：{{ question.author.username }}</span>
        <span>时间：{{ question.create_time }}</span>
      </p>
      <hr>
      <p class="question-content">{{ question.content }}</p>
      <hr>

      <h4 class="comment-group-title">评论（{{ question.answers|length }}）：</h4>
      <form action="{{ url_for('qa.answer',question_id=question.id) }}" method="post">
        <div class="form-group">
          <input type="text" placeholder="请填写评论" name="content" class="form-control">
        </div>
        {% for message in get_flashed_messages() %}
          <div class="form-group">
            <div class="text-danger">{{ message }}</div>
          </div>
        {% endfor %}
        <div class="form-group" style="text-align: right;">
          <button class="btn btn-primary">评论</button>
        </div>
      </form>
      <ul class="comment-group">
        {% for answer in question.answers %}
          <li>
            <div class="user-info">
              <img class="avatar" src="{{ url_for('static',filename='image/img.jpg') }}" alt="">
              <span class="username">{{ answer.author.username }}</span>
              <span class="create-time">{{ answer.create_time }}</span>
            </div>
            <p class="comment-content">{{ answer.content }}</p>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}知了问答-首页{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
{% endblock %}

{% block body %}
  <div class="row" style="margin-top: 20px;">
    <div class="col"></div>
    <div class="col-8">
      <ul class="question-ul">
        {% for question in questions %}
          <li>
            <div class="side-question">
              <img class="side-question-avatar" src="{{ url_for('static',filename='image/img.jpg') }}" alt="">
            </div>
            <div class="question-main">
              <div class="question-title"><a href="{{ url_for('qa.question_detail',question_id=question.id) }}">{{ question.title }}</a></div>
              <div class="question-content">{{ question.content }}</div>
              <div class="question-detail">
                <span class="question-author">{{ question.author.username }}</span>
                <span class="question-time">{{ question.create_time }}</span>
              </div>
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}python问答-登录{% endblock %}


{% block head %}

{% endblock %}


{% block body %}
<div class="row mt-4">
    <div class="col"></div>
    <div class="col">
<form action="{{ url_for('user.login') }}" method="POST">
    <div class="form-group ">
    <label for="exampleInputEmail1">邮箱</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
    <small id="emailHelp" class="form-text text-muted">邮箱仅用于登录</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">密码</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
    {% for message in get_flashed_messages() %}
    <div class="form-group">
        <div class="text-danger">{{ message }}</div>
    </div>
    {% endfor %}


  <button type="submit" class="btn btn-primary btn-block">登录</button>
</form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

templates/public_question.html
{% extends "base.html" %}

{% block title %}发布问答{% endblock %}

{% block head %}
<script type="text/javascript" src="static/showdown-master/dist/showdown.min.js"></script>
{% endblock %}

<style>
    body {
      font-family: "Helvetica Neue", Helvetica, Microsoft Yahei, Hiragino Sans GB, WenQuanYi Micro Hei, sans-serif;
     font-size: 16px;
      line-height: 1.42857143;
      color: #333;
      background-color: #fff;
    }
    ul li {
        line-height: 24px;
    }
    blockquote {
        border-left:#eee solid 5px;
        padding-left:20px;
    }
    code {
        color:#D34B62;
        background: #F9F2F4;
    }
</style>

{% block body %}
<div class="row" style="margin-top: 20px;">
    <div class="col"></div>
    <div class="col-8">
        <h1 style="text-align: center">发布问答</h1>
        <form action="{{ url_for('qa.public_question')}}" method="post">
            <div class="form-group">
                <input type="text" name="title" class="form-control" placeholder="请输入标题(不小于2字)">
            </div>
            <div class="form-group">
                <textarea name="content" class="form-control" rows="17" placeholder="请输入内容(不小于5字)"></textarea>
            </div>

            {% for message in get_flashed_messages() %}
            <div class="form-group">
                <div class="text-danger">{{ message }}</div>
            </div>
            {% endfor %}
            <div class="form-group" style="text-align: right;">
                <button class="btn btn-primary">发布</button>
            </div>
        </form>
    </div>
    <div class="col"></div>
</div>


{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}python问答-注册{% endblock %}


{% block head %}
<script src="{{ url_for('static', filename='jquery/jquery.3.6.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/register.js') }}"></script>
{% endblock %}


{% block body %}
<div class="row mt-4">
    <div class="col"></div>
    <div class="col">
<form method="POST" action="{{ url_for('user.register') }}">
    <div class="form-group ">
    <label for="exampleInputEmail1">邮箱</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
    <small id="emailHelp" class="form-text text-muted">邮箱仅用于登录</small>
  </div>
  <div class="form-group ">
    <label for="exampleInputEmail1">验证码</label>
    <div class="input-group">
        <input type="text" class="form-control" name="captcha">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
        </div>
    </div>
  </div>
  <div class="form-group ">
    <label for="exampleInputEmail1">用户名</label>
    <input type="text" class="form-control" name="username">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">密码</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">确认密码</label>
    <input type="password" class="form-control" id="exampleInputPassword2" name="password_confirm">
  </div>
  <button type="submit" class="btn btn-primary btn-block">登录</button>
</form>
    </div>
    <div class="col"></div>
</div>

{% endblock %}